see the content...
pcgeek86/PSGitHub pull request #30
Opened 2017-01-14 11:19 UTC by chantisnake

# Bug Fixes

- Fix a bug that when uses Invoke-GitHubApi with a header that already included `header` that this will cause error

# Improvements / Enhancements

- Add `-preview` switch to `Invoke-GitHubApi` to enable Preview Api #29 
- Explicitly request v3 api, see: https://developer.github.com/v3/#current-version
- Add verbose output for request body, this makes debug a little easier
- Add `Get-GitHubLicense` function 

To improve visibility of this Pull Request, make sure to mention one of the project administrators, using `@githubusername` syntax.

2017-02-13 13:16 UTC, chantisnake commented
hello?

2017-02-15 23:23 UTC, pcgeek86 requested changes
Please review the comments and make changes as appropriate.

2017-02-15 23:23 UTC, pcgeek86 commented on Functions/Private/Invoke-GitHubApi.ps1
> +        Write-Verbose "the request body is {0}" -f $Body
Please use named parameters and parentheses as necessary.

2017-02-15 23:23 UTC, pcgeek86 commented on Functions/Public/Get-GitHubLicense.ps1
> +            $restMethod = "licenses/{0}" -f $LicenseId
Please use single quotes unless double quotes are absolutely necessary. In this case, they aren't.

2017-02-15 23:23 UTC, pcgeek86 commented on Functions/Private/Invoke-GitHubApi.ps1
> +        Write-Warning 'The API you are trying to retrive maybe preview'
Please use named parameters, not positional.

2017-02-18 11:29 UTC, chantisnake commented
a fix is pushed. Thank you.

2017-02-21 16:17 UTC, merged

2017-02-21 16:17 UTC, pcgeek86 commented
@chantisnake Thanks!